# Generated by Django 5.1.15 on 2026-09-12 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoComputo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_correo', models.EmailField(max_length=254, verbose_name='correo de quien registra')),
                ('responsable', models.CharField(choices=[('bodega_bello', 'Bodega Bello'), ('bodega_medellin', 'Bodega Medellín'), ('tecnico_1', 'Técnico 1 (reemplazar por el nombre real)'), ('tecnico_2', 'Técnico 2 (reemplazar por el nombre real)')], max_length=40, verbose_name='técnico o almacén responsable')),
                ('marca', models.CharField(choices=[('apple', 'Apple'), ('hp', 'HP'), ('dell', 'Dell'), ('lenovo', 'Lenovo'), ('asus', 'ASUS'), ('acer', 'Acer'), ('msi', 'MSI'), ('toshiba', 'Toshiba'), ('otra', 'Otra')], max_length=20)),
                ('marca_otra', models.CharField(blank=True, max_length=40, verbose_name='marca (si eligió Otra)')),
                ('procesador', models.CharField(choices=[('intel_i3', 'Intel Core i3'), ('intel_i5', 'Intel Core i5'), ('intel_i7', 'Intel Core i7'), ('intel_i9', 'Intel Core i9'), ('ryzen_3', 'AMD Ryzen 3'), ('ryzen_5', 'AMD Ryzen 5'), ('ryzen_7', 'AMD Ryzen 7'), ('apple_silicon', 'Apple M1 / M2 / M3'), ('otro', 'Otro')], max_length=20)),
                ('procesador_otro', models.CharField(blank=True, max_length=60, verbose_name='procesador (si eligió Otro)')),
                ('ram', models.CharField(choices=[('4', '4 GB'), ('8', '8 GB'), ('16', '16 GB'), ('32', '32 GB'), ('mas_32', 'Más de 32 GB')], max_length=10, verbose_name='memoria RAM')),
                ('almacenamiento_tipo', models.CharField(choices=[('hdd', 'HDD'), ('ssd', 'SSD'), ('nvme', 'NVMe')], max_length=10, verbose_name='tipo de almacenamiento')),
                ('almacenamiento_capacidad', models.CharField(choices=[('128', '128 GB'), ('256', '256 GB'), ('480', '480 GB'), ('512', '512 GB'), ('1000', '1 TB'), ('2000', '2 TB'), ('mas_2000', 'Más de 2 TB')], max_length=10, verbose_name='capacidad de almacenamiento')),
                ('estado_bateria', models.CharField(choices=[('nueva', 'Nueva'), ('mayor_80', 'Vida útil > 80% (Muy buena)'), ('entre_50_80', 'Vida útil 50% - 80% (Regular)'), ('menor_50', 'Vida útil < 50% (Requiere cambio pronto)'), ('no_aplica', 'No aplica (equipo de escritorio)')], max_length=20, verbose_name='estado de la batería')),
                ('estado_estetico', models.PositiveSmallIntegerField(choices=[(1, 'Con daños estéticos visibles / Desgastado'), (2, 'Marcas de uso notorias'), (3, 'Buen estado, con marcas leves'), (4, 'Muy buen estado, casi sin marcas'), (5, 'Como nuevo / Impecable')], verbose_name='estado estético (1 a 5)')),
                ('garantia_meses', models.PositiveSmallIntegerField(choices=[(3, '3 meses'), (6, '6 meses'), (12, '12 meses')], verbose_name='garantía')),
                ('costo_compra', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='costo de compra (interno)')),
                ('precio_venta', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='precio de venta al público')),
                ('notas_fallas', models.TextField(blank=True, verbose_name='detalles adicionales o fallas')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('vendido', 'Vendido')], default='borrador', max_length=10)),
                ('fecha_venta', models.DateTimeField(blank=True, null=True, verbose_name='fecha en que se marcó vendido')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'equipo de cómputo',
                'verbose_name_plural': 'equipos de cómputo',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='FotoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='equipos/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.equipocomputo')),
            ],
            options={
                'verbose_name': 'foto del equipo',
                'verbose_name_plural': 'fotos del equipo',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
