# Generated by Django 5.1.15 on 2026-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoequipo',
            name='miniatura',
            field=models.ImageField(blank=True, upload_to='equipos/', verbose_name='foto (versión para la tarjeta)'),
        ),
        migrations.AlterField(
            model_name='fotoequipo',
            name='imagen',
            field=models.ImageField(upload_to='equipos/', verbose_name='foto (vista de detalle)'),
        ),
    ]
